### ISSUE TITLE
Crashes Atmosphere

### ISSUE THREAD

**Issue by noob0503** [Scandal-UK/Incognito_RCM#5]
Thanks for the update 0.6.6 (https://github.com/Scandal-UK/Incognito_RCM/releases/download/v0.6.6/Incognito_RCM.bin). I used it with the latest package from sdsetup.com, it was able to incognito the emunand, but the atmosphere could not get loaded. I re-formatted the SD card, prepared all over again, re-tried, same result. Wondering if you could please spare some time and look into it. Firmware:10.0.4, US Region. Many thanks in advance!

**Comment by bao3** [comment]
> Thanks for the update 0.6.6 (https://github.com/Scandal-UK/Incognito_RCM/releases/download/v0.6.6/Incognito_RCM.bin). I used it with the latest package from sdsetup.com, it was able to incognito the emunand, but the atmosphere could not get loaded. I re-formatted the SD card, prepared all over again, re-tried, same result. Wondering if you could please spare some time and look into it. Firmware:10.0.4, US Region. Many thanks in advance!

Perhaps , you need patches , and inject with Hekate.bin , not fusee-primary.bin . I got the same issue ,it’s not about Incognito .

**Comment by Scandal-UK** [comment]
I do not think that Incognito has caused an issue here.

Here is the best way to set-up Atmosphere from scratch - you can then boot using either the Hekate or fusee-primary payloads.

- Download latest Hekate
- Extract "bootloader" folder to SD card
- Inject the Hekate bin payload

**Create emuMMC partition:**
- In Hekate, select "Tools"
- Select "Archive bit * AutoRCM * Touch Tuning"
- Select "Partition SD Card"
- Drag slider for "emuMMC (RAW)" so it's 29GB then "Next Step"
- Select "Start", wait then tap OK and close

**Create emuMMC:**
- In Hekate, tap "emuMMC"
- Select "Create emuMMC"
- Select "SD Partition"
- Select "Part 1", wait then select "Close" when done
- emuMMC info should show enabled, if not change emuMMC to SD RAW1

**Install Atmosphere:**
- Download and extract the latest Atmosphere folders to the SD (delete any older versions of the "Atmosphere" and "sept" folders if they exist)
- Install sigpatches for fusee-primary - currently found at https://gbatemp.net/threads/sigpatches-for-atmosphere-fusee-primary-only.567542/
- Download the latest **fusee-primary.bin** and place it in `SD:/bootloader/payloads`
- Create a file named **hekate_ipl.ini** in the `SD:/bootloader` folder
- Add the following text to **hekate_ipl.ini**;

```[config]
autoboot=1
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=0
autonogc=1

{------- Launch -------}
[Atmosphere]
payload=bootloader/payloads/fusee-primary.bin
icon=bootloader/res/icon_atmosphere.bmp

[Horizon]
fss0=atmosphere/fusee-secondary.bin
stock=1
icon=bootloader/res/icon_horizon.bmp
```

_(Optional)_ **Replace reboot-payload with Hekate:**
- Delete the file `SD:/Atmosphere/reboot_payload.bin`
- Copy the Hekate bin payload to `SD:/Atmosphere` and rename it to **reboot_payload.bin**
