### ISSUE TITLE
unknown pkg1 version under FW 11.0.0 / Incognito_RCM v0.6.6

### ISSUE THREAD

**Issue by muxi1** [Scandal-UK/Incognito_RCM#6]
Hello Scandal_UK,
it seems that Incognito_RCM v0.6.6 does not work under FW 11.0.0. A message appears regarding an unknown pkg1 version.

**Comment by omegar1999** [comment]
hi, did you solve the error in the end?

**Comment by carcaschoi** [comment]
have problem too with 11.0.1

**Comment by Scandal-UK** [comment]
I am running end-to-end tests and then I will release the latest version!
